import type { Module } from './module.ts';
import { module as transferFn } from './modules/transfer-fn/module.ts';
import { module as pidTuner } from './modules/pid-tuner/module.ts';
import { module as routhHurwitz } from './modules/routh-hurwitz/module.ts';
import { module as fourierSeries } from './modules/fourier-series/module.ts';
import { module as bjtAmp } from './modules/bjt-amp/module.ts';
import { module as bjtDc } from './modules/bjt-dc/module.ts';
import { module as diodeShaping } from './modules/diode-shaping/module.ts';
import { module as fetAmp } from './modules/fet-amp/module.ts';
import { module as opamp } from './modules/opamp/module.ts';
import { module as multistage } from './modules/multistage/module.ts';
import { module as diffAmp } from './modules/diff-amp/module.ts';
import { module as feedback } from './modules/feedback/module.ts';
import { module as freqResponse } from './modules/freq-response/module.ts';
import { module as activeFilter } from './modules/active-filter/module.ts';
import { module as powerAmp } from './modules/power-amp/module.ts';
import { module as oscillator } from './modules/oscillator/module.ts';
import { module as comparator } from './modules/comparator/module.ts';
import { module as smpsBuck } from './modules/smps-buck/module.ts';
import { module as smpsBoost } from './modules/smps-boost/module.ts';
import { module as smpsBuckBoost } from './modules/smps-buckboost/module.ts';
import { module as smpsFlyback } from './modules/smps-flyback/module.ts';
import { module as smpsForward } from './modules/smps-forward/module.ts';
import { module as planeWaveIncidence } from './modules/plane-wave-incidence/module.ts';
import { module as impedanceMatching } from './modules/impedance-matching/module.ts';

export const modules: Module[] = [transferFn, pidTuner, routhHurwitz, fourierSeries, bjtAmp, bjtDc, diodeShaping, fetAmp, opamp, multistage, diffAmp, feedback, freqResponse, activeFilter, powerAmp, oscillator, comparator, smpsBuck, smpsBoost, smpsBuckBoost, smpsFlyback, smpsForward, planeWaveIncidence, impedanceMatching];
